
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Base extends javax.swing.JFrame {
public LoginPage signIn = null;
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

    /**
     * Creates new form Base
     */
    public Base() {
        initComponents();
            //setExtendedState(Base.MAXIMIZED_BOTH);
            setBounds(0,0,screenSize.width, screenSize.height);
    setLocation(screenSize.width/2-getWidth()/2, screenSize.height/2-getHeight()/2);
    setVisible(true);

            this.setTitle("Astron");
        //initComponents();
        //Toolkit toolkit = getToolkit();
        //Dimension size = toolkit.getScreenSize();
        //pack();
        //setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2;
     
        signIn = new LoginPage();
        if(LoginPage.toDisplayName==1){
            display_name();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        signInMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        message_signIn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("Software_logo.jpeg")).getImage());
        setName("Astron"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(215, 232, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(signInMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 1353, 1680, 19));

        jPanel1.setBackground(new java.awt.Color(31, 35, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignUp.setBackground(new java.awt.Color(239, 40, 83));
        btnSignUp.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 280, -1));

        log_out.setBackground(new java.awt.Color(239, 40, 83));
        log_out.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        log_out.setForeground(new java.awt.Color(255, 255, 255));
        log_out.setText("Log Out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        jPanel1.add(log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 280, -1));

        btnSignIn.setBackground(new java.awt.Color(239, 40, 83));
        btnSignIn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("log in");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 280, -1));

        jButton1.setBackground(new java.awt.Color(239, 40, 83));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Forgot Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 280, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 300, 810));

        message_signIn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jPanel2.add(message_signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 40, 368, 28));

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel6.setText("ASTRON");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Astron_logo.jpeg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 160, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updation.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clearence.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/display.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collection.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data entry.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 1811, 780));

        getAccessibleContext().setAccessibleName("Astron");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
signIn.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignInActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
message_signIn.setText("");
LogIn_First lg=new LogIn_First();
Logout_successful log=new Logout_successful();
        if(LoginPage.toDisplayName==0){
            //LogIn_First lg=new LogIn_First();
            lg.setVisible(true);
        }
        else{
                        //Logout_successful log=new Logout_successful();
                        log.setVisible(true);
        }     
        LoginPage.access=false; 
        LoginPage.toDisplayName=0;        // TODO add your handling code here:
    }//GEN-LAST:event_log_outActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
SignUp signup=new SignUp();
signup.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Forgot_Password page=new Forgot_Password(); 
page.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked


        if(signIn.getAccessValue()){
            currentStockForm2 obj1=new currentStockForm2();
           obj1.setVisible(true);
        }
        else{
            LogIn_First lg=new LogIn_First();
            lg.setVisible(true);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        if(signIn.getAccessValue()){
            new currentStockForm3().setVisible(true);
          
        }
        else{
            LogIn_First lg=new LogIn_First();
            lg.setVisible(true);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        if(signIn.getAccessValue()){
           new currentStockForm4part2().setVisible(true); 
           
        }
        else{
            LogIn_First lg=new LogIn_First();
            lg.setVisible(true);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked


        if(signIn.getAccessValue()){
           new Collection1().setVisible(true); 
           
        }
        else{
            new LogIn_First().setVisible(true);
            
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       
       
       if(signIn.getAccessValue()){
            currentStockForm1 obj1=new currentStockForm1();
           obj1.setVisible(true);
        }
        else{
            LogIn_First lg=new LogIn_First();
            lg.setVisible(true);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked
public void display_name(){
        if(signIn.getAccessValue()){
               message_signIn.setText("Hello, "+(new LoginPage()).name);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton log_out;
    private javax.swing.JLabel message_signIn;
    private javax.swing.JLabel signInMessage;
    // End of variables declaration//GEN-END:variables
}
