

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class currentStockForm1 extends javax.swing.JFrame {
static int user_rights_binary=0;

Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

    /** Creates new form cureentStockForm1 */
    public currentStockForm1() {
        initComponents();
    setLocation(screenSize.width/2-getWidth()/2, screenSize.height/2-getHeight()/2);
    setVisible(true);
    //User_Rights();
        base.setEditable(false);
        base.setRenderer(new Demo(base.getRenderer()));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        
        
        
    }
    /*public void User_Rights(){
       // System.out.println(LoginPage.name);
        try{  
                int a=1;
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6414727","sql6414727","aq6eT6kxTQ");
                String selQuery="SELECT * FROM login_details where  username=? and Admin=?";
                PreparedStatement pst=con.prepareStatement(selQuery);
                pst.setString(1,LoginPage.name);
                pst.setInt(2,a);
                ResultSet rs=pst.executeQuery();
                if(rs.next()){
                    user_rights_binary=1;
                }
                else{
                    user_rights_binary=0;
                }
                //System.out.println(user_rights_binary);
            }
            catch (ClassNotFoundException ex) {
                System.out.println(ex.getMessage());
            } catch (SQLException ex) {
                //Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            } 
    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        base = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        design = new javax.swing.JTextField();
        rms = new javax.swing.JTextField();
        gr = new javax.swing.JTextField();
        mill = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        next = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insert");
        setBackground(new java.awt.Color(165, 191, 198));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("Software_logo.jpeg")).getImage());

        jPanel1.setBackground(new java.awt.Color(31, 35, 71));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 950));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Base:");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Design:");

        jLabel3.setText("RMS:");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GR:");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mill:");

        base.setBackground(new java.awt.Color(249, 173, 129));
        base.setEditable(true);
        base.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        base.setForeground(new java.awt.Color(255, 255, 255));
        base.setMaximumRowCount(7);
        base.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Balatan Butta Rich Pallu", "Raw Slub Butta Rich Pallu", "Balatan Butta Chit Pallu", "Raw Slub Butta Chit Pallu", "Balatan Embose Chit Pallu", "Raw Slub all Over Butta", " " }));
        base.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        base.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baseMouseClicked(evt);
            }
        });
        base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total:");

        design.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N

        rms.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N

        gr.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N

        mill.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        mill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                millActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        total.setMaximumSize(new java.awt.Dimension(32767, 32767));
        total.setMinimumSize(new java.awt.Dimension(100, 100));
        total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalMouseClicked(evt);
            }
        });
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 138, 115));
        reset.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        next.setBackground(new java.awt.Color(255, 138, 115));
        next.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        insert.setBackground(new java.awt.Color(255, 138, 115));
        insert.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data Entry ");

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RMS:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel8)
                        .addGap(70, 70, 70)
                        .addComponent(rms, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(insert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4)
                        .addGap(80, 80, 80)
                        .addComponent(gr, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5)
                        .addGap(60, 60, 60)
                        .addComponent(mill, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(design, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reset))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(design, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(rms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insert))
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(gr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(next)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(mill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
String n1=rms.getText();
String n2=gr.getText();
String n3=mill.getText();
int add=Integer.parseInt(n1)+Integer.parseInt(n2)+Integer.parseInt(n3);
total.setText(add+"");
// TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed
class Demo extends DefaultListCellRenderer{
    // TODO add your handling code here:
    private ListCellRenderer defaultRenderer;
    public Demo(ListCellRenderer defaultRenderer){
        this.defaultRenderer=defaultRenderer;
        
    }
    public Component getListCellRendererComponent(JList list,Object value,int index,boolean isSelected,boolean cellHasFocus){
        Component c = defaultRenderer.getListCellRendererComponent(list, value,
        index, isSelected, cellHasFocus);
    if (c instanceof JLabel) {
      if (isSelected) {
        c.setBackground(new Color(249,40,83));
      } else {
        c.setBackground(Color.white);
      }
    } else {
      c.setBackground(Color.black);
      c = super.getListCellRendererComponent(list, value, index, isSelected,
          cellHasFocus);
    }
        return c;
    }
}
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        base.setSelectedIndex(0);
        design.setText("");
        rms.setText("");
        gr.setText("");
        mill.setText("");
        total.setText("");
    }//GEN-LAST:event_resetActionPerformed
/*public void dialogue(){
        UIManager uimanager = new UIManager();
        uimanager.put("OptionPane.messageFont", new FontUIResource(new Font("Copperplate Gothic Bold", Font.BOLD, 18))); //to change message font
        uimanager.put("OptionPane.background", new ColorUIResource(192, 164, 241)); 
        uimanager.put("OptionPane.errorDialog.titlePane.background",Color.pink);//to change background color
        //uimanager.put("OptionPane.messageDialog.titlePane.background", new ColorUIResource(192, 164, 241));// to change text label background
        //uimanager.put("Panel.background", new ColorUIResource(192, 164, 241));
        //uimanager.put("OptionPane.okButtonText", "hehe"); //to change text of ok button
        
        uimanager.put("OptionPane.messageForeground", Color.red);  //to change text color
}*/
    private void millActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_millActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_millActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed

    if(design.getText().trim().isEmpty() || rms.getText().trim().isEmpty() || gr.getText().trim().isEmpty() || mill.getText().trim().isEmpty()){
    /*JDialog.setDefaultLookAndFeelDecorated(true);
UIManager.put("OptionPane.minimumSize",new Dimension(350,200));
UIManager.put("OptionPane.background", Color.gray);
UIManager.put("Panel.background", Color.lightGray);
UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.black);
UIManager.put("OptionPane.errorDialog.titlePane.background", Color.pink);
UIManager.put("OptionPane.errorDialog.border.background", Color.white);
            JOptionPane.showMessageDialog(null, "Field(s) are empty.","Warning",0);*/
   new  AlertBox_FieldEmpty().setVisible(true);
        }
else if(Pattern.matches("^[0-9]+$",design.getText())){
    new Correct_Design().setVisible(true);
    design.setText("");
    design.grabFocus();
}
        else if(!Pattern.matches("^[0-9]+$",rms.getText())){
            new Invalid_Format().setVisible(true);
             rms.setText("");
             rms.grabFocus();
        }
        else if(!Pattern.matches("^[0-9]+$",gr.getText())){
            new Invalid_Format().setVisible(true);
             gr.setText("");
             gr.grabFocus();
        }
        else if(!Pattern.matches("^[0-9]+$",mill.getText())){
            new Invalid_Format().setVisible(true);
             mill.setText("");
             mill.grabFocus();
        }
// TODO add your handling code here:
        else{
            //System.out.println(login.getIsAdmin());
            
        try{      
          
     Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con;
    con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_bYz4P","u159657273_9OFDL","Vaishnavi$2801");
    //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    String SelectedBase=base.getSelectedItem().toString();
    
    String query = null;
    String selectQuery=null;
            switch(SelectedBase){
                case "Balatan Butta Rich Pallu":
                    query="insert into balatan_rich_pallu(Design, RMS, GR, Mill, Total) values(?,?,?,?,?)";
                    selectQuery="select * from balatan_rich_pallu where Design='"+design.getText()+"'";
                    break;
                case "Raw Slub Butta Rich Pallu":
                    query="insert into raw_rich_pallu(Design, RMS, GR, Mill, Total) values(?,?,?,?,?)";
                    selectQuery="select * from raw_rich_pallu where Design='"+design.getText()+"'";
                    break;
                case "Balatan Butta Chit Pallu":
                    query="insert into balatan_chit_pallu(Design, RMS, GR, Mill, Total) values(?,?,?,?,?)";
                    selectQuery="select * from balatan_chit_pallu where Design='"+design.getText()+"'";
                    break;
                case "Raw Slub Butta Chit Pallu":
                    query="insert into raw_chit_pallu(Design, RMS, GR, Mill, Total) values(?,?,?,?,?)";
                    selectQuery="select * from raw_chit_pallu where Design='"+design.getText()+"'";
                    break;
                case "Balatan Embose Chit Pallu":
                    query="insert into embose_chit_pallu(Design, RMS, GR, Mill, Total) values(?,?,?,?,?)";
                    selectQuery="select * from embose_chit_pallu where Design='"+design.getText()+"'";
                    break;
                case "Raw Slub all Over Butta":
                    query="insert into all_over_butta(Design, RMS, GR, Mill, Total) values(?,?,?,?,?)";
                    selectQuery="select * from all_over_butta where Design='"+design.getText()+"'";
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Please choose base!!!");
            }
            int x=0,y=0,z=0;
            if(rms.getText().isEmpty()==false){
                x=Integer.parseInt(rms.getText());
            }
            if(gr.getText().isEmpty()==false){
                y=Integer.parseInt(gr.getText());
            }
            if(mill.getText().isEmpty()==false){
                z=Integer.parseInt(mill.getText());
            }
            x=x+y+z; 
            total.setText(String.valueOf(x));
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, design.getText().trim().toUpperCase());
            pst.setString(2, rms.getText().trim());
            pst.setString(3, gr.getText().trim());
            pst.setString(4, mill.getText().trim());
            pst.setString(5, total.getText().trim());
            ResultSet rs = pst.executeQuery(selectQuery);
            
            if(rs.next()==false){
                pst.executeUpdate();
                
                new InsertedSuccessfully().setVisible(true);
            }
            else{
                new Already_Added().setVisible(true);
            }
        }
        catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
        }
            

        
    }//GEN-LAST:event_insertActionPerformed
    
    private void totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_totalMouseClicked

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        new currentStockForm2();
        dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseActionPerformed
    
    private void baseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMouseClicked

    }//GEN-LAST:event_baseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currentStockForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currentStockForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currentStockForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currentStockForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
/*currentStockForm1 f1=new currentStockForm1();
f1.dialogue();/*
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currentStockForm1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> base;
    private javax.swing.JTextField design;
    private javax.swing.JTextField gr;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mill;
    private javax.swing.JButton next;
    private javax.swing.JButton reset;
    private javax.swing.JTextField rms;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

}
