
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class OrderForm extends javax.swing.JFrame {

    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        initComponents();
        FillAgentCombo();
         FillCombo();
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_combo2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        formNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        agent_dropbox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        base = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        sareesParcels = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        paymentDays = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalSarees = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalParcels = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rate = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        insertRow = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        i_want_to = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Date:");

        jLabel2.setText("Party:");

        name_combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---select party---" }));
        name_combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_combo2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Order Form No.");

        formNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formNoActionPerformed(evt);
            }
        });

        jLabel4.setText("Agent:");

        jLabel5.setText("Quality:");

        base.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Balatan Butta Rich Pallu", "Balatan Butta Chit Pallu", "Raw Slub Butta Rich Pallu", "Raw Slub Butta Chit Pallu", "Balatan Embose Chit Pallu", "Raw Slub all Over Butta" }));
        base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseActionPerformed(evt);
            }
        });

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Quality", "Sr. No", "Design", "Sarees", "Parcels"
            }
        ));
        jScrollPane1.setViewportView(displayTable);

        jLabel6.setText("Sarees/Parcels:");

        jLabel7.setText("Payment Days:");

        jLabel8.setText("Total sarees:");

        jLabel9.setText("Total Parcels:");

        jLabel10.setText("Rate:");

        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        pdf.setText("Create PDF ");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });

        insertRow.setText("Insert Row");
        insertRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertRowActionPerformed(evt);
            }
        });

        jLabel11.setText("I want to:");

        i_want_to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insert table data", "Insert form data", "Insert all data together", "Search by Date", "Search by Quality and Date", "Delete order data", "Update order data", " " }));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel11)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(i_want_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(formNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(name_combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agent_dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(165, 165, 165)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentDays, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sareesParcels, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(insertRow)
                                .addGap(41, 41, 41)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(41, 41, 41)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(145, 145, 145))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalSarees, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalParcels, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(i_want_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agent_dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(name_combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sareesParcels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)
                        .addComponent(paymentDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(totalSarees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(totalParcels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(insert)
                                    .addComponent(update))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(delete)
                                    .addComponent(reset))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(insertRow)
                                    .addComponent(search)))
                            .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pdf)
                        .addGap(179, 179, 179))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
try{
    Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con;
    con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    java.util.Date d3=date.getDate();
    String newDate3=formatter.format(d3);
    String SelectedBase=base.getSelectedItem().toString();
    String party=name_combo2.getSelectedItem().toString();
    String agent=agent_dropbox.getSelectedItem().toString();
    if(i_want_to.getSelectedIndex()==1){
    String query1="insert into order_form(Date,PartyName,Agent_name,form_no,payment_days,rate,sareesParcels,Quality) values (?,?,?,?,?,?,?,?)";
    PreparedStatement pst1=con.prepareStatement(query1);
    pst1.setString(1,newDate3);
    pst1.setString(2,party);
    pst1.setString(3,agent);
    pst1.setString(4,formNo.getText());
    pst1.setString(5,paymentDays.getText());
    pst1.setString(6,rate.getText());
    pst1.setString(7,sareesParcels.getText());
    pst1.setString(8,SelectedBase);
    pst1.executeUpdate();
    }
    else if(i_want_to.getSelectedIndex()==0){
    int rows=displayTable.getRowCount();
    //System.out.println(rows);
    for(int row=0;row<rows;row++){
       
        String date1=(String) displayTable.getValueAt(row,0);
        String quality=(String) displayTable.getValueAt(row,1);
        String srno=(String)displayTable.getValueAt(row,2);
        String design=(String)displayTable.getValueAt(row,3);
        String sarees=(String)displayTable.getValueAt(row,4);
        String parcels=(String)displayTable.getValueAt(row,5);
   
    if((date1=="" || date1==null)&&(quality=="" ||quality==null)){
    String query2="insert into order_details(PartyName,Date,SrNumber,Design,Quality,sarees,parcels) values(?,?,?,?,?,?,?)";
    PreparedStatement pst2=con.prepareStatement(query2);
    pst2.setString(1,party);
    pst2.setString(2,newDate3);
    pst2.setString(3,srno);
     pst2.setString(4,design);
      pst2.setString(5,SelectedBase);
       pst2.setString(6,sarees);
       pst2.setString(7, parcels);
       
       pst2.executeUpdate();
    }
    
    }
    }
    else if(i_want_to.getSelectedIndex()==2){
        String query1="insert into order_form(Date,PartyName,Agent_name,form_no,payment_days,rate,sareesParcels,Quality) values (?,?,?,?,?,?,?,?)";
    PreparedStatement pst1=con.prepareStatement(query1);
    pst1.setString(1,newDate3);
    pst1.setString(2,party);
    pst1.setString(3,agent);
    pst1.setString(4,formNo.getText());
    pst1.setString(5,paymentDays.getText());
    pst1.setString(6,rate.getText());
    pst1.setString(7,sareesParcels.getText());
    pst1.setString(8,SelectedBase);
    pst1.executeUpdate();
    int rows=displayTable.getRowCount();
    //System.out.println(rows);
    for(int row=0;row<rows;row++){
       
        String date1=(String) displayTable.getValueAt(row,0);
        String quality=(String) displayTable.getValueAt(row,1);
        String srno=(String)displayTable.getValueAt(row,2);
        String design=(String)displayTable.getValueAt(row,3);
        String sarees=(String)displayTable.getValueAt(row,4);
        String parcels=(String)displayTable.getValueAt(row,5);
   
    if((date1=="" || date1==null)&&(quality=="" ||quality==null)){
    String query2="insert into order_details(PartyName,Date,SrNumber,Design,Quality,sarees,parcels) values(?,?,?,?,?,?,?)";
    PreparedStatement pst2=con.prepareStatement(query2);
    pst2.setString(1,party);
    pst2.setString(2,newDate3);
    pst2.setString(3,srno);
     pst2.setString(4,design);
      pst2.setString(5,SelectedBase);
       pst2.setString(6,sarees);
       pst2.setString(7, parcels);
       
       pst2.executeUpdate();
    }
    
    }
    }
    
    new InsertedSuccessfully().setVisible(true);
    
}
 catch(Exception e){
            System.out.println(e.getMessage());

        }
    // TODO add your handling code here:
    }//GEN-LAST:event_insertActionPerformed

    private void formNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formNoActionPerformed

    private void insertRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertRowActionPerformed
TableModel model=displayTable.getModel(); 
DefaultTableModel dtm=(DefaultTableModel)model;
dtm.addRow(new Object[] {"","","","","",""});// TODO add your handling code here:
    }//GEN-LAST:event_insertRowActionPerformed

    private void baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseActionPerformed

    // TODO add your handling code here:
    }//GEN-LAST:event_baseActionPerformed

    private void name_combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_combo2ActionPerformed
show_user();        // TODO add your handling code here:
    }//GEN-LAST:event_name_combo2ActionPerformed

    
    
    private void reset(){
        date.setDate(null);
        name_combo2.setSelectedIndex(0);
        agent_dropbox.setSelectedIndex(0);
        sareesParcels.setText("");
        formNo.setText("");
        base.setSelectedIndex(0);
        paymentDays.setText("");
        rate.setText("");
    }
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
try{
            Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con;
    con = DriverManager.getConnection("jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");
    DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
            int row = displayTable.getSelectedRow();
            String date=(String)displayTable.getValueAt(row,0);
            String srno=(String)displayTable.getValueAt(row,2);
            String query="delete from order_details where SrNumber=? and Date=?";
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1,srno);
            pst.setString(2,date);
            pst.executeUpdate();
            new Deleted_record().setVisible(true);
            model.removeRow(row);
}
catch(Exception e){
            System.out.println(e.getMessage());
        
        }// TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
reset();        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
if(i_want_to.getSelectedIndex()==3){
    show_date_user();
}
else if(i_want_to.getSelectedIndex()==4){
    show_date_quality_user();
}// TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
try{  
       Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con;
    con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");
           TableModel model=displayTable.getModel();
             String query="Update order_details SET Design=?,sarees=?,parcels=? where PartyName=? and Date=? and SrNumber=? and Quality=?";
             PreparedStatement pst=con.prepareStatement(query);
             /*SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
            java.util.Date d3=date.getDate();
            String newDate3=formatter.format(d3);*/
            
             int row=displayTable.getSelectedRow();
             System.out.print(row);
           
            pst.setString(1,model.getValueAt(row,3).toString().trim());
            pst.setString(2,model.getValueAt(row,4).toString().trim());
            pst.setString(3,model.getValueAt(row,5).toString().trim());
            pst.setString(4,name_combo2.getSelectedItem().toString());
            pst.setString(5,model.getValueAt(row,0).toString());
            pst.setString(6,model.getValueAt(row,2).toString().trim());
            pst.setString(7,model.getValueAt(row,1).toString().trim());
            pst.executeUpdate();
new Update_record().setVisible(true);
    }        catch(Exception e){
                    System.out.println(e.getMessage());     
         }           // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
      try{
           Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con;
    con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");
          java.util.Date d3=date.getDate();
          String SelectedBase=name_combo2.getSelectedItem().toString();
    String quality=base.getSelectedItem().toString();
          SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    String newDate3=formatter.format(d3);
        JasperDesign jd=JRXmlLoader.load("D:\\Team Cadmus\\Astron\\src\\orderforms.jrxml");  
        String query="select * from order_form where Date='"+newDate3+"' and PartyName='"+name_combo2.getSelectedItem().toString()+"' and Quality='"+base.getSelectedItem().toString()+"'";
        String query2="select * from order_details od NATURAL JOIN order_form ofrm WHERE (od.PartyName='"+name_combo2.getSelectedItem().toString()+"') and (od.Date='"+newDate3+"') and (od.Quality='"+base.getSelectedItem().toString()+"') and(ofrm.PartyName=od.PartyName) and (ofrm.Date=od.Date) and (ofrm.Quality=od.Quality)";
 String query3="select SUM(sarees),SUM(parcels) from order_details od NATURAL JOIN order_form ofrm WHERE (od.PartyName='"+name_combo2.getSelectedItem().toString()+"') and (od.Date='"+newDate3+"') and (od.Quality='"+base.getSelectedItem().toString()+"') and(ofrm.PartyName=od.PartyName) and (ofrm.Date=od.Date) and (ofrm.Quality=od.Quality)";       
       
       //pst2.executeQuery();
JRDesignQuery newQuery=new JRDesignQuery();
        newQuery.setText(query2);
        jd.setQuery(newQuery);
        
        HashMap<String,Object> para = new HashMap<>();
        PreparedStatement pst=con.prepareStatement(query);
        PreparedStatement pst3=con.prepareStatement(query3);
                ResultSet rs=pst.executeQuery();
                ResultSet rs3=pst3.executeQuery();
                int form_no=0,payment_days=0,sareesParcels=0,totalSarees=0,totalParcels=0;
                String agent_name="",rate="";
                while(rs3.next()){
                    totalSarees=rs3.getInt(1);
                    totalParcels=rs3.getInt(2);
                }
                System.out.println(totalSarees);
                System.out.println(totalParcels);
                while(rs.next()){
                    form_no=rs.getInt("form_no");
                    payment_days=rs.getInt("payment_days");
                    sareesParcels=rs.getInt("sareesParcels");
                    agent_name=rs.getString("Agent_name");
                    rate=rs.getString("rate");
                }
                System.out.print(form_no);
                para.put("form_no",form_no);
                para.put("payment_days",payment_days);
                para.put("sareesParcels",sareesParcels);
                para.put("Agent_name",agent_name);
                para.put("rate",rate);
                para.put("PartyName",name_combo2.getSelectedItem().toString());
                para.put("Date",date.getDate());
                para.put("Quality",base.getSelectedItem().toString());
                para.put("sarees",totalSarees);
                para.put("parcels",totalParcels);
                
                JasperReport js=JasperCompileManager.compileReport(jd);
                JasperPrint jPrint=JasperFillManager.fillReport(js,para,con);
                JasperViewer.viewReport(jPrint,false);
                 
      }
      catch(Exception e){
                    System.out.println(e.getMessage());     
         }    
        
        
        
        
 
        
        
        
    }//GEN-LAST:event_pdfActionPerformed
public ArrayList<orderDetails> date_quality_specific_order(){
        ArrayList<orderDetails> orderList3=new ArrayList<orderDetails>();
        DefaultTableModel model=(DefaultTableModel)displayTable.getModel();
    while(model.getRowCount()>0){
        for (int i=0;i<model.getRowCount(); i++){
                model.removeRow(i);
    }
    }
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con;
    con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");
    
    String SelectedBase=name_combo2.getSelectedItem().toString();
    String quality=base.getSelectedItem().toString();
    orderDetails od;
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    java.util.Date d3=date.getDate();
    String newDate3=formatter.format(d3);
    //System.out.print(newDate3);
    String query="select * from order_details od NATURAL JOIN order_form ofrm WHERE (od.PartyName=?) and (od.Date=?) and (od.Quality=?) and(ofrm.PartyName=od.PartyName) and (ofrm.Date=od.Date) and (ofrm.Quality=od.Quality)";
    
    PreparedStatement pst=con.prepareStatement(query);
   
    pst.setString(1,SelectedBase);
    pst.setString(2,newDate3);
    pst.setString(3,quality);
    ResultSet rs=pst.executeQuery();
   
    while(rs.next()){
        od=new orderDetails(rs.getString("Date"),rs.getString("SrNumber"),rs.getString("Design"),rs.getString("Quality"),rs.getString("sarees"),rs.getString("parcels"),rs.getString("Agent_name"),rs.getString("form_no"),rs.getString("payment_days"),rs.getString("rate"),rs.getString("sareesParcels"));
        orderList3.add(od);
        }
    }
    catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    return orderList3;
    }
public void show_date_quality_user(){
        ArrayList<orderDetails> list3=date_quality_specific_order();
        DefaultTableModel model=(DefaultTableModel)displayTable.getModel();
    String[] row=new String[6];
    int total_sarees=0,total_parcels=0;
    for(int i=0;i<list3.size();i++){
                row[0]=list3.get(i).getDate();
                row[1]=list3.get(i).getQuality();
                row[2]=list3.get(i).getSrNo();
            row[3]=list3.get(i).getDesign();
            row[4]=list3.get(i).getSarees();
             row[5]=list3.get(i).getParcels();
             formNo.setText(list3.get(i).getform());
             agent_dropbox.setSelectedItem(list3.get(i).getAgent());
             sareesParcels.setText(list3.get(i).getSareesParcels());
             rate.setText(list3.get(i).getRate());
             paymentDays.setText(list3.get(i).getPayment());
             
             
             model.addRow(row);
        total_sarees=total_sarees+Integer.parseInt(row[4]);
        total_parcels=total_parcels+Integer.parseInt(row[5]);
    }
    totalSarees.setText(String.valueOf(total_sarees));
   totalParcels.setText(String.valueOf(total_parcels));
    }
    
    public ArrayList<order> date_specific_order(){
        ArrayList<order> orderList2=new ArrayList<order>();
        DefaultTableModel model=(DefaultTableModel)displayTable.getModel();
    while(model.getRowCount()>0){
        for (int i=0;i<model.getRowCount(); i++){
                model.removeRow(i);
    }
    }
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con;
    con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");
    
    String SelectedBase=name_combo2.getSelectedItem().toString();
    order od;
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    java.util.Date d3=date.getDate();
    String newDate3=formatter.format(d3);
    
    String query="select * from order_details where PartyName=? and Date=?";
    PreparedStatement pst=con.prepareStatement(query);
    pst.setString(1,SelectedBase);
    pst.setString(2,newDate3);
    ResultSet rs=pst.executeQuery();
    while(rs.next()){
        od=new order(rs.getString("Date"),rs.getString("SrNumber"),rs.getString("Design"),rs.getString("Quality"),rs.getString("sarees"),rs.getString("parcels"));
        orderList2.add(od);
        }
    }
    catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    return orderList2;
    }
    public void show_date_user(){
        ArrayList<order> list2=date_specific_order();
        DefaultTableModel model=(DefaultTableModel)displayTable.getModel();
    String[] row=new String[6];
    int total_sarees=0,total_parcels=0;
    for(int i=0;i<list2.size();i++){
                row[0]=list2.get(i).getDate();
                row[1]=list2.get(i).getQuality();
                row[2]=list2.get(i).getSrNo();
            row[3]=list2.get(i).getDesign();
            row[4]=list2.get(i).getSarees();
             row[5]=list2.get(i).getParcels();
             
             model.addRow(row);
        total_sarees=total_sarees+Integer.parseInt(row[4]);
        total_parcels=total_parcels+Integer.parseInt(row[5]);
    }
    totalSarees.setText(String.valueOf(total_sarees));
   totalParcels.setText(String.valueOf(total_parcels));
    }
    
    public ArrayList<order> order(){
        ArrayList<order> orderList=new ArrayList<>();
        DefaultTableModel model=(DefaultTableModel)displayTable.getModel();
    while(model.getRowCount()>0){
        for (int i=0;i<model.getRowCount(); i++){
                model.removeRow(i);
    }
    }
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
     Connection con;
    con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");
    
    String SelectedBase=name_combo2.getSelectedItem().toString();
    order od;
    String query="select * from order_details where PartyName=?";
    PreparedStatement pst=con.prepareStatement(query);
    pst.setString(1,SelectedBase);
    ResultSet rs=pst.executeQuery();
    while(rs.next()){
        od=new order(rs.getString("Date"),rs.getString("SrNumber"),rs.getString("Design"),rs.getString("Quality"),rs.getString("sarees"),rs.getString("parcels"));
        orderList.add(od);
        }
    }
    catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    return orderList;
    }
    public void show_user(){
        ArrayList<order> list=order();
        DefaultTableModel model=(DefaultTableModel)displayTable.getModel();
    String[] row=new String[6];
    int total_sarees=0,total_parcels=0;
    for(int i=0;i<list.size();i++){
                row[0]=list.get(i).getDate();
                row[1]=list.get(i).getQuality();
                row[2]=list.get(i).getSrNo();
            row[3]=list.get(i).getDesign();
            row[4]=list.get(i).getSarees();
             row[5]=list.get(i).getParcels();
             
             model.addRow(row);
        total_sarees=total_sarees+Integer.parseInt(row[4]);
        total_parcels=total_parcels+Integer.parseInt(row[5]);
    }
    totalSarees.setText(String.valueOf(total_sarees));
   totalParcels.setText(String.valueOf(total_parcels));
    }
    public void sortarraylist(){
        ArrayList<agents> list =getAgents();
        
        
    }
    
    public ArrayList<agents> getAgents(){
        ArrayList<agents> AgentList=new ArrayList<>();
    DefaultComboBoxModel model = new DefaultComboBoxModel(); 
    model.setSelectedItem("---select agent---");
    try{
         
         
        Class.forName("com.mysql.cj.jdbc.Driver");
     
     Connection con;
    con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");
    String query="select DISTINCT agent1,agent2,agent3 from party_details";
    agents ag;
    PreparedStatement pst=con.prepareStatement(query);
    ResultSet rs=pst.executeQuery();
    while(rs.next()){
        ag=new agents(rs.getString("agent1"),rs.getString("agent2"),rs.getString("agent3"));
        AgentList.add(ag);
    }
    
    
    }
    catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
   
 
    return AgentList;
}
public void FillCombo(){
    DefaultComboBoxModel model = new DefaultComboBoxModel(); 
    int count=0;
    int compare=0;
    boolean added;
    Object obj;
    model.setSelectedItem("---select party---");
    try{
         
         
        Class.forName("com.mysql.cj.jdbc.Driver");
     
     Connection con;
    con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");
    
    String sql="select PartyName from party_table";
    PreparedStatement pst=con.prepareStatement(sql);
    ResultSet rs=pst.executeQuery();
    while(rs.next()){
            added=false;
        String name=rs.getString("PartyName");
        count=name_combo2.getItemCount();
        for (int i = 0; i < count; i++) {
           obj = name_combo2.getItemAt(i);
           compare = name.compareToIgnoreCase(obj.toString());
           if (compare <= 0) { 
               name_combo2.insertItemAt(name, i);
               added = true;
               break;
          }
      }
      if (!added) {
          name_combo2.addItem(name);
      }
        
        
    }
    
    //con.close();
    //pst.close();
    }
    catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    public void FillAgentCombo(){
    DefaultComboBoxModel model = new DefaultComboBoxModel(); 

    model.setSelectedItem("---select agent---");
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con;
        con = DriverManager.getConnection(
            "jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");

        String sql="select DISTINCT agent1,agent2,agent3 from party_details";
        PreparedStatement pst=con.prepareStatement(sql);
        ResultSet rs=pst.executeQuery();
        Set<String> agentNames = new HashSet<>();
        while(rs.next()){
            String name1=rs.getString("agent1");
            String name2=rs.getString("agent2");
            String name3=rs.getString("agent3");
            if(name1 == null ? String.valueOf(0) != null : !name1.equals(String.valueOf(0))){
                agentNames.add(name1);
            }
            if(name2 == null ? String.valueOf(0) != null : !name2.equals(String.valueOf(0))){
                agentNames.add(name2);
            }
            if(name3 == null ? String.valueOf(0) != null : !name3.equals(String.valueOf(0))){
                agentNames.add(name3);
            }
        }
        ArrayList<String> agentList = new ArrayList<>(agentNames);
        java.util.Collections.sort(agentList);
//      for(String agent: agentList)
//          System.out.println(agent);
        for(String agent: agentList){
            model.addElement(agent);
        }
        agent_dropbox.setModel(model);
    //con.close();
    //pst.close();
    }
    catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agent_dropbox;
    private javax.swing.JComboBox<String> base;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton delete;
    private javax.swing.JTable displayTable;
    private javax.swing.JTextField formNo;
    private javax.swing.JComboBox<String> i_want_to;
    private javax.swing.JButton insert;
    private javax.swing.JButton insertRow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> name_combo2;
    private javax.swing.JTextField paymentDays;
    private javax.swing.JButton pdf;
    private javax.swing.JTextField rate;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sareesParcels;
    private javax.swing.JButton search;
    private javax.swing.JTextField totalParcels;
    private javax.swing.JTextField totalSarees;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    
}
