
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Outstanding extends javax.swing.JFrame {
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    /**
     * Creates new form Outstanding
     */
    public Outstanding() {
        initComponents();
        setSize(1000,700);
        setLocation(screenSize.width/2-getWidth()/2, screenSize.height/2-getHeight()/2);
        show_user();
        jScrollPane1.getViewport().setBackground(new Color(116,121,180));
        TableCellRenderer alteredColorRenderer = new AlterColor();
        party_agent_table.setDefaultRenderer(Object.class, alteredColorRenderer);
        headerColorAndWidth();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    public final void headerColorAndWidth(){
        DefaultTableCellRenderer headerClr = new DefaultTableCellRenderer();
        headerClr.setBackground(new Color(255, 138, 115));
       // headerClr.setForeground(Color.decode("#FCE7FC"));
       party_agent_table.setRowHeight(party_agent_table.getRowHeight()+20);
               

        party_agent_table.getTableHeader().getColumnModel().getColumn(0).setHeaderRenderer(headerClr);
        party_agent_table.getTableHeader().getColumnModel().getColumn(1).setHeaderRenderer(headerClr);
        party_agent_table.getTableHeader().getColumnModel().getColumn(2).setHeaderRenderer(headerClr);
        
        JTableHeader tableHeader = party_agent_table.getTableHeader();
        tableHeader.setVisible(true);
        tableHeader.setFont(new Font("Copperplate Gothic Bold",1, 18));
        tableHeader.setOpaque(false); 
        tableHeader.setForeground(new Color(255,255,255));
        TableColumn tc1=party_agent_table.getColumnModel().getColumn(0);
        tc1.setPreferredWidth(250);
        TableColumn tc2=party_agent_table.getColumnModel().getColumn(1);
        tc2.setPreferredWidth(100);
        TableColumn tc3=party_agent_table.getColumnModel().getColumn(2);
        tc3.setPreferredWidth(150);
        
    }
    public ArrayList<DataParty> userList(){
        ArrayList<DataParty> usersList=new ArrayList<>();
        DefaultTableModel model=(DefaultTableModel)party_agent_table.getModel();
        while (model.getRowCount()>0){
            for (int i=0;i<model.getRowCount(); i++){
                model.removeRow(i);
            }
        }
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");  
             Connection con=DriverManager.getConnection("jdbc:mysql://sql452.main-hosting.eu:3306/u159657273_astron","u159657273_user1","Vaishnavi$2801");  
             String query="SELECT PartyName ,SUM(Outstanding)  as Outstanding,Agent from collection1 group by PartyName,Agent";
             Statement st=con.createStatement();
             ResultSet rs=st.executeQuery(query); 
             DataParty user;
             while(rs.next()){
                 user=new DataParty(rs.getString("PartyName"),rs.getString("Outstanding"),rs.getString("Agent"));
                 usersList.add(user);
             }
         }
         catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
         }
         return usersList;
    }
     public void show_user(){
        ArrayList<DataParty> list=userList();
        DefaultTableModel model=(DefaultTableModel)party_agent_table.getModel();
        String []row=new String[4];
        int outstandingtotal=0;
        for(int i=0;i<list.size();i++){
           row[0]=list.get(i).getname();
           row[1]=list.get(i).getoutstanding();
           row[2]=list.get(i).getagent();
           model.addRow(row);
           outstandingtotal=outstandingtotal+Integer.parseInt(row[1]);

        }
        outstanding_total.setText(String.valueOf(outstandingtotal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        party_agent_table = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        outstanding_total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 35, 71));

        party_agent_table.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        party_agent_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Party Name", "Outstanding", "Agent"
            }
        ));
        jScrollPane1.setViewportView(party_agent_table);

        refresh.setBackground(new java.awt.Color(255, 138, 115));
        refresh.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        outstanding_total.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Outstanding total:");

        jButton1.setBackground(new java.awt.Color(255, 138, 115));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jButton1.setText("print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outstanding_total, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outstanding_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(refresh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
show_user();        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               MessageFormat header=new MessageFormat("Outstanding List");
        try{
           party_agent_table.print(JTable.PrintMode.FIT_WIDTH,header,null); 
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Outstanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Outstanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Outstanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Outstanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Outstanding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField outstanding_total;
    private javax.swing.JTable party_agent_table;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
