/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saree.application.gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hii
 */
public class Party_Agent_Form7 extends javax.swing.JFrame {

    /**
     * Creates new form party_agent_form7
     */
    public Party_Agent_Form7() {
        initComponents();
        show_user();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        party_agent_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        party_agent_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "Party Name", "Outstanding Amount", "Agent Name"
            }
        ));
        party_agent_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                party_agent_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(party_agent_table);
        if (party_agent_table.getColumnModel().getColumnCount() > 0) {
            party_agent_table.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(78, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(68, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void party_agent_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_party_agent_tableMouseClicked
        // TODO add your handling code here:
        show_user();
    }//GEN-LAST:event_party_agent_tableMouseClicked
    public ArrayList<Party_Agent> userList(){
        ArrayList<Party_Agent> usersList=new ArrayList<>();
        DefaultTableModel model=(DefaultTableModel)party_agent_table.getModel();
        while (model.getRowCount()>0){
            for (int i=0;i<model.getRowCount(); i++){
                model.removeRow(i);
            }
        }
         try{
             Class.forName("com.mysql.cj.jdbc.Driver");  
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/?user=root","root","Iloveher");  
             String query="SELECT Party_Name ,SUM(Outstanding_Amount) as Outstanding_Amount,Agent_Name from testdb.collection group by Party_Name,Agent_Name";
             Statement st=con.createStatement();
             ResultSet rs=st.executeQuery(query); 
             Party_Agent user;
             while(rs.next()){
                 user=new Party_Agent(rs.getString("Party_Name"),rs.getString("Outstanding_Amount"),rs.getString("Agent_Name"));
                 usersList.add(user);
             }
         }
         catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
         }
         return usersList;
    }
     public void show_user(){
        ArrayList<Party_Agent> list=userList();
        DefaultTableModel model=(DefaultTableModel)party_agent_table.getModel();
        String []row=new String[4];
        for(int i=0;i<list.size();i++){
           row[1]=list.get(i).getParty_name();
           row[2]=list.get(i).getOutstanding_amount();
           row[3]=list.get(i).getAgent_name();
           model.addRow(row);
        }
    }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Party_Agent_Form7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Party_Agent_Form7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Party_Agent_Form7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Party_Agent_Form7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Party_Agent_Form7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable party_agent_table;
    // End of variables declaration//GEN-END:variables
}
